apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hno3vfu5z-java-springboot
  janus-idp.io/tekton: hno3vfu5z-java-springboot
  backstage.io/kubernetes-id: hno3vfu5z-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: hno3vfu5z-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
