apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: hno3vfu5z-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-springboot:1487387cf5fa1bf46ac3f23adea16e1c5eda12b0@sha256:682bfdf4f84c43ee0f262b6a1e0f54f08f3230c847dfa8f175b30481690986cb
          name: container-image
